### ISSUE TITLE
Not an Issue , File History

### ISSUE THREAD

**Issue by julesbrat** [ChrisTitusTech/ChrisTitusTech#7]
HI, would love this as part of your tool 
the ability to turn on File History on Windows 10/11 Pro

i currently share out a folder on my machine the map network drive in the File History Network Location
localhost/filehistory

then i am able to turn this feature on which enables File History Restore

hope this can be added or a better way of working so that i could enable on workstations etc

Cheers Jules
Learning Lots watching your  Videos

**Comment by 101br03k** [comment]
please request this in the repository of the winutil: https://github.com/ChrisTitusTech/winutil
